/*******************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.test.jit;

import io.questdb.cairo.vm.Vm;
import io.questdb.cairo.vm.api.MemoryCARW;
import io.questdb.jit.*;
import io.questdb.std.MemoryTag;
import io.questdb.std.Numbers;
import io.questdb.std.Unsafe;
import org.junit.Assert;
import org.junit.Test;

import static io.questdb.jit.CompiledFilterIRSerializer.*;

/**
 * Tests the full pipeline: IR -> IrDecoder -> IrLowering -> ScalarBytecodeFilterCompiler.
 * Each test compares the generated bytecode filter against the VectorFilterInterpreter
 * oracle to verify parity.
 */
public class ScalarBytecodeFilterCompilerTest {

    private static final int SCALAR_OPTIONS = (2 << 1); // log2(4), scalar hint, no null checks
    private static final int NULL_CHECK_OPTIONS = (2 << 1) | (1 << 6); // scalar + null checks

    // ========================
    // Integer comparisons
    // ========================

    @Test
    public void testIntGt() throws Exception {
        // col0 > 5
        assertParityIntCol(new int[]{3, 7, 5, 10, 1, 6}, ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS);
    }

    @Test
    public void testIntEq() throws Exception {
        // col0 = 5
        assertParityIntCol(new int[]{5, 3, 5, 0, 5}, ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(EQ, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS);
    }

    @Test
    public void testIntLe() throws Exception {
        // col0 <= 3
        assertParityIntCol(new int[]{1, 3, 5, 0, 4, 3}, ir(
                insn(IMM, I4_TYPE, 3, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(LE, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS);
    }

    @Test
    public void testIntArithmeticAndCompare() throws Exception {
        // (col0 + col1) > 10
        assertParityTwoIntCols(
                new int[]{3, 7, 2, 8},
                new int[]{8, 1, 9, 5},
                ir(
                        insn(IMM, I4_TYPE, 10, 0),
                        insn(MEM, I4_TYPE, 0, 0),
                        insn(MEM, I4_TYPE, 1, 0),
                        insn(ADD, 0, 0, 0),
                        insn(GT, 0, 0, 0),
                        insn(RET, 0, 0, 0)
                ), SCALAR_OPTIONS
        );
    }

    @Test
    public void testIntBooleanAnd() throws Exception {
        // col0 > 2 AND col0 < 8
        assertParityIntCol(new int[]{1, 3, 5, 8, 2, 7}, ir(
                insn(IMM, I4_TYPE, 2, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(IMM, I4_TYPE, 8, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(LT, 0, 0, 0),
                insn(AND, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS);
    }

    @Test
    public void testIntBooleanOr() throws Exception {
        // col0 < 2 OR col0 > 8
        assertParityIntCol(new int[]{1, 5, 9, 2, 0, 8}, ir(
                insn(IMM, I4_TYPE, 2, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(LT, 0, 0, 0),
                insn(IMM, I4_TYPE, 8, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(OR, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS);
    }

    @Test
    public void testIntNeg() throws Exception {
        // -col0 > -3 (i.e., col0 < 3)
        assertParityIntCol(new int[]{1, 3, 5, 2, 4, 0}, ir(
                insn(IMM, I4_TYPE, -3, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(NEG, 0, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS);
    }

    @Test
    public void testIntNot() throws Exception {
        // NOT (col0 > 5) => col0 <= 5
        assertParityIntCol(new int[]{3, 7, 5, 10, 1, 6}, ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(NOT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS);
    }

    // ========================
    // Mixed-type comparisons
    // ========================

    @Test
    public void testMixedI4I8Comparison() throws Exception {
        // IMM I8 100, MEM I4 col0, EQ -> promotes I4 to I8
        assertParityIntCol(new int[]{100, 50, 100, 0}, ir(
                insn(IMM, I8_TYPE, 100, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(EQ, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS);
    }

    // ========================
    // Bind variable tests
    // ========================

    @Test
    public void testBindVariableIntEq() throws Exception {
        // VAR I4 0, MEM I4 col0, EQ
        assertParityIntColWithVar(
                new int[]{5, 3, 5, 0, 5},
                new long[]{5}, // bind var value
                ir(
                        insn(VAR, I4_TYPE, 0, 0),
                        insn(MEM, I4_TYPE, 0, 0),
                        insn(EQ, 0, 0, 0),
                        insn(RET, 0, 0, 0)
                ), SCALAR_OPTIONS
        );
    }

    // ========================
    // Count-only mode
    // ========================

    @Test
    public void testCountOnlyIntGt() throws Exception {
        // col0 > 5, count-only
        int[] data = {3, 7, 5, 10, 1, 6};
        IrDecoder.Instruction[] instructions = ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );

        long colData = allocIntColumn(data);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        Unsafe.getUnsafe().putLong(colPtrArray, colData);

        try {
            LoweredProgram prog = IrLowering.lower(instructions, SCALAR_OPTIONS);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);

            long count = filter.countRows(colPtrArray, 1, 0, 0, 0, data.length);

            // Interpreter oracle
            long expectedCount = interpreterCount(instructions, SCALAR_OPTIONS, colPtrArray, 1, 0, 0, 0, data.length);

            Assert.assertEquals(expectedCount, count);
        } finally {
            Unsafe.free(colData, (long) data.length * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
        }
    }

    // ========================
    // Mixed type (int vs float) tests
    // ========================

    @Test
    public void testMixedIntFloatComparison() throws Exception {
        // col0 (I4) > 2.5 (F8) — the serializer promotes I4 to F8
        // IR: IMM F8 2.5, MEM I4 col0, GT, RET
        IrDecoder.Instruction[] instructions = ir(
                new IrDecoder.Instruction(IMM, F8_TYPE, Double.doubleToRawLongBits(2.5), 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );

        // This is a scalar program (mixed sizes), no null checks
        int options = (3 << 1); // log2(8)=3, scalar hint
        assertParityIntCol(new int[]{1, 3, 2, 5, 0}, instructions, options);
    }

    @Test
    public void testFloatConstantComparison() throws Exception {
        // col0 (F4) > 3.14 (F4)
        IrDecoder.Instruction[] instructions = ir(
                new IrDecoder.Instruction(IMM, F4_TYPE, Double.doubleToRawLongBits(3.14), 0),
                new IrDecoder.Instruction(MEM, F4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );

        int options = (2 << 1) | (1 << 4); // log2(4), single-size
        float[] data = {1.0f, 4.0f, 3.14f, 5.0f, 2.0f};
        long colData = Unsafe.malloc((long) data.length * Float.BYTES, MemoryTag.NATIVE_DEFAULT);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long expectedBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        for (int i = 0; i < data.length; i++) {
            Unsafe.getUnsafe().putFloat(colData + (long) i * Float.BYTES, data[i]);
        }
        Unsafe.getUnsafe().putLong(colPtrArray, colData);

        try {
            long expected = interpreterFilter(instructions, options, colPtrArray, 1, 0, 0, 0, expectedBuf, data.length);

            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            if (filter == null) {
                return; // unsupported, skip
            }
            long actual = filter.filterRows(colPtrArray, 1, 0, 0, 0, outputBuf, data.length);

            Assert.assertEquals("row count mismatch", expected, actual);
        } finally {
            Unsafe.free(colData, (long) data.length * Float.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(expectedBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        }
    }

    // ========================
    // Byte (I1) type tests
    // ========================

    @Test
    public void testByteEq() throws Exception {
        // col0 == 3 (byte column)
        byte[] data = {3, 1, 3, 2};
        long colData = Unsafe.malloc(data.length, MemoryTag.NATIVE_DEFAULT);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long expectedBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        for (int i = 0; i < data.length; i++) {
            Unsafe.getUnsafe().putByte(colData + i, data[i]);
        }
        Unsafe.getUnsafe().putLong(colPtrArray, colData);

        IrDecoder.Instruction[] instructions = ir(
                insn(IMM, I1_TYPE, 3, 0),
                insn(MEM, I1_TYPE, 0, 0),
                insn(EQ, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );
        int options = (0 << 1) | (1 << 4); // I1 single-size

        try {
            long expected = interpreterFilter(instructions, options, colPtrArray, 1, 0, 0, 0, expectedBuf, data.length);

            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            Assert.assertNotNull("filter should be supported", filter);
            long actual = filter.filterRows(colPtrArray, 1, 0, 0, 0, outputBuf, data.length);

            Assert.assertEquals("row count mismatch", expected, actual);
            for (long i = 0; i < actual; i++) {
                Assert.assertEquals("row mismatch at index " + i,
                        Unsafe.getUnsafe().getLong(expectedBuf + i * 8),
                        Unsafe.getUnsafe().getLong(outputBuf + i * 8));
            }
        } finally {
            Unsafe.free(colData, data.length, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(expectedBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        }
    }

    // ========================
    // Empty and boundary cases
    // ========================

    @Test
    public void testEmptyInput() throws Exception {
        IrDecoder.Instruction[] instructions = ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );

        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        try {
            LoweredProgram prog = IrLowering.lower(instructions, SCALAR_OPTIONS);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            long matched = filter.filterRows(colPtrArray, 1, 0, 0, 0, outputBuf, 0);
            Assert.assertEquals(0, matched);
        } finally {
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, 8, MemoryTag.NATIVE_DEFAULT);
        }
    }

    // ========================
    // Helpers
    // ========================

    private void assertParityIntCol(int[] data, IrDecoder.Instruction[] instructions, int options) throws Exception {
        long colData = allocIntColumn(data);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long expectedBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        Unsafe.getUnsafe().putLong(colPtrArray, colData);

        try {
            // Interpreter oracle
            long expected = interpreterFilter(instructions, options, colPtrArray, 1, 0, 0, 0, expectedBuf, data.length);

            // Bytecode under test
            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            long actual = filter.filterRows(colPtrArray, 1, 0, 0, 0, outputBuf, data.length);

            Assert.assertEquals("row count mismatch", expected, actual);
            for (long i = 0; i < actual; i++) {
                long expRow = Unsafe.getUnsafe().getLong(expectedBuf + i * 8);
                long actRow = Unsafe.getUnsafe().getLong(outputBuf + i * 8);
                Assert.assertEquals("row mismatch at index " + i, expRow, actRow);
            }
        } finally {
            Unsafe.free(colData, (long) data.length * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(expectedBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        }
    }

    private void assertParityTwoIntCols(int[] data0, int[] data1, IrDecoder.Instruction[] instructions, int options) throws Exception {
        assert data0.length == data1.length;
        int len = data0.length;
        long col0 = allocIntColumn(data0);
        long col1 = allocIntColumn(data1);
        long colPtrArray = Unsafe.malloc(16, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) len * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long expectedBuf = Unsafe.malloc((long) len * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        Unsafe.getUnsafe().putLong(colPtrArray, col0);
        Unsafe.getUnsafe().putLong(colPtrArray + 8, col1);

        try {
            long expected = interpreterFilter(instructions, options, colPtrArray, 2, 0, 0, 0, expectedBuf, len);

            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            long actual = filter.filterRows(colPtrArray, 2, 0, 0, 0, outputBuf, len);

            Assert.assertEquals("row count mismatch", expected, actual);
            for (long i = 0; i < actual; i++) {
                Assert.assertEquals("row mismatch at index " + i,
                        Unsafe.getUnsafe().getLong(expectedBuf + i * 8),
                        Unsafe.getUnsafe().getLong(outputBuf + i * 8));
            }
        } finally {
            Unsafe.free(col0, (long) len * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(col1, (long) len * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 16, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) len * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(expectedBuf, (long) len * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        }
    }

    private void assertParityIntColWithVar(int[] data, long[] varValues, IrDecoder.Instruction[] instructions, int options) throws Exception {
        long colData = allocIntColumn(data);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long expectedBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long varsMem = Unsafe.malloc((long) varValues.length * 8, MemoryTag.NATIVE_DEFAULT);
        Unsafe.getUnsafe().putLong(colPtrArray, colData);
        for (int i = 0; i < varValues.length; i++) {
            Unsafe.getUnsafe().putLong(varsMem + (long) i * 8, varValues[i]);
        }

        try {
            long expected = interpreterFilter(instructions, options, colPtrArray, 1, 0, varsMem, varValues.length, expectedBuf, data.length);

            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            long actual = filter.filterRows(colPtrArray, 1, 0, varsMem, varValues.length, outputBuf, data.length);

            Assert.assertEquals("row count mismatch", expected, actual);
            for (long i = 0; i < actual; i++) {
                Assert.assertEquals("row mismatch at index " + i,
                        Unsafe.getUnsafe().getLong(expectedBuf + i * 8),
                        Unsafe.getUnsafe().getLong(outputBuf + i * 8));
            }
        } finally {
            Unsafe.free(colData, (long) data.length * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(expectedBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(varsMem, (long) varValues.length * 8, MemoryTag.NATIVE_DEFAULT);
        }
    }

    private static long allocIntColumn(int[] data) {
        long mem = Unsafe.malloc((long) data.length * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
        for (int i = 0; i < data.length; i++) {
            Unsafe.getUnsafe().putInt(mem + (long) i * Integer.BYTES, data[i]);
        }
        return mem;
    }

    private static long interpreterFilter(
            IrDecoder.Instruction[] instructions, int options,
            long colPtrArray, long colCount, long varSizeAux,
            long varsAddr, long varsCount,
            long outputBuf, int rowCount
    ) throws Exception {
        try (MemoryCARW irMem = Vm.getCARWInstance(1024, 1, MemoryTag.NATIVE_JIT)) {
            writeIr(irMem, instructions);
            VectorFilterInterpreter interp = new VectorFilterInterpreter();
            interp.compile(irMem, options);
            return interp.filter(colPtrArray, colCount, varSizeAux, varsAddr, varsCount, outputBuf, rowCount);
        }
    }

    private static long interpreterCount(
            IrDecoder.Instruction[] instructions, int options,
            long colPtrArray, long colCount, long varSizeAux,
            long varsAddr, long varsCount, int rowCount
    ) throws Exception {
        try (MemoryCARW irMem = Vm.getCARWInstance(1024, 1, MemoryTag.NATIVE_JIT)) {
            writeIr(irMem, instructions);
            VectorFilterInterpreter interp = new VectorFilterInterpreter();
            interp.compile(irMem, options);
            return interp.filterCount(colPtrArray, colCount, varSizeAux, varsAddr, varsCount, rowCount);
        }
    }

    private static void writeIr(MemoryCARW mem, IrDecoder.Instruction[] instructions) {
        for (IrDecoder.Instruction insn : instructions) {
            mem.putInt(insn.opcode());
            mem.putInt(insn.type());
            mem.putLong(insn.payloadLo());
            mem.putLong(insn.payloadHi());
        }
    }

    private static IrDecoder.Instruction[] ir(IrDecoder.Instruction... instructions) {
        return instructions;
    }

    private static IrDecoder.Instruction insn(int opcode, int type, long lo, long hi) {
        return new IrDecoder.Instruction(opcode, type, lo, hi);
    }
}
