/*******************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.test.jit;

import io.questdb.jit.*;
import io.questdb.std.MemoryTag;
import io.questdb.std.Unsafe;
import org.junit.Assert;
import org.junit.Test;

import static io.questdb.jit.CompiledFilterIRSerializer.*;

/**
 * Tests the full pipeline: IR -> IrDecoder -> IrLowering -> ScalarBytecodeFilterCompiler.
 * Each test verifies the generated bytecode filter against hardcoded
 * expected row indices computed from the input data.
 */
public class ScalarBytecodeFilterCompilerTest {

    private static final int SCALAR_OPTIONS = (2 << 1); // log2(4), scalar hint, no null checks
    private static final int NULL_CHECK_OPTIONS = (2 << 1) | (1 << 6); // scalar + null checks

    // ========================
    // Integer comparisons
    // ========================

    @Test
    public void testIntGt() throws Exception {
        // col0 > 5: data [3, 7, 5, 10, 1, 6] → rows 1(7), 3(10), 5(6)
        assertIntColResult(new int[]{3, 7, 5, 10, 1, 6}, ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS, new long[]{1, 3, 5});
    }

    @Test
    public void testIntEq() throws Exception {
        // col0 = 5: data [5, 3, 5, 0, 5] → rows 0, 2, 4
        assertIntColResult(new int[]{5, 3, 5, 0, 5}, ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(EQ, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS, new long[]{0, 2, 4});
    }

    @Test
    public void testIntLe() throws Exception {
        // col0 <= 3: data [1, 3, 5, 0, 4, 3] → rows 0(1), 1(3), 3(0), 5(3)
        assertIntColResult(new int[]{1, 3, 5, 0, 4, 3}, ir(
                insn(IMM, I4_TYPE, 3, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(LE, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS, new long[]{0, 1, 3, 5});
    }

    @Test
    public void testIntArithmeticAndCompare() throws Exception {
        // (col0 + col1) > 10: data0 [3,7,2,8], data1 [8,1,9,5]
        // sums: 11, 8, 11, 13 → rows 0(11), 2(11), 3(13)
        assertTwoIntColsResult(
                new int[]{3, 7, 2, 8},
                new int[]{8, 1, 9, 5},
                ir(
                        insn(IMM, I4_TYPE, 10, 0),
                        insn(MEM, I4_TYPE, 0, 0),
                        insn(MEM, I4_TYPE, 1, 0),
                        insn(ADD, 0, 0, 0),
                        insn(GT, 0, 0, 0),
                        insn(RET, 0, 0, 0)
                ), SCALAR_OPTIONS, new long[]{0, 2, 3}
        );
    }

    @Test
    public void testIntBooleanAnd() throws Exception {
        // col0 > 2 AND col0 < 8: data [1,3,5,8,2,7] → rows 1(3), 2(5), 5(7)
        assertIntColResult(new int[]{1, 3, 5, 8, 2, 7}, ir(
                insn(IMM, I4_TYPE, 2, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(IMM, I4_TYPE, 8, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(LT, 0, 0, 0),
                insn(AND, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS, new long[]{1, 2, 5});
    }

    @Test
    public void testIntBooleanOr() throws Exception {
        // col0 < 2 OR col0 > 8: data [1,5,9,2,0,8] → rows 0(1), 2(9), 4(0)
        assertIntColResult(new int[]{1, 5, 9, 2, 0, 8}, ir(
                insn(IMM, I4_TYPE, 2, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(LT, 0, 0, 0),
                insn(IMM, I4_TYPE, 8, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(OR, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS, new long[]{0, 2, 4});
    }

    @Test
    public void testIntNeg() throws Exception {
        // -col0 > -3 (i.e., col0 < 3): data [1,3,5,2,4,0] → rows 0(1), 3(2), 5(0)
        assertIntColResult(new int[]{1, 3, 5, 2, 4, 0}, ir(
                insn(IMM, I4_TYPE, -3, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(NEG, 0, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS, new long[]{0, 3, 5});
    }

    @Test
    public void testIntNot() throws Exception {
        // NOT (col0 > 5) => col0 <= 5: data [3,7,5,10,1,6] → rows 0(3), 2(5), 4(1)
        assertIntColResult(new int[]{3, 7, 5, 10, 1, 6}, ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(NOT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS, new long[]{0, 2, 4});
    }

    // ========================
    // Mixed-type comparisons
    // ========================

    @Test
    public void testMixedI4I8Comparison() throws Exception {
        // IMM I8 100, MEM I4 col0, EQ → promotes I4 to I8: rows 0(100), 2(100)
        assertIntColResult(new int[]{100, 50, 100, 0}, ir(
                insn(IMM, I8_TYPE, 100, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(EQ, 0, 0, 0),
                insn(RET, 0, 0, 0)
        ), SCALAR_OPTIONS, new long[]{0, 2});
    }

    // ========================
    // Bind variable tests
    // ========================

    @Test
    public void testBindVariableIntEq() throws Exception {
        // VAR(5) == col0: data [5,3,5,0,5] → rows 0, 2, 4
        assertIntColWithVarResult(
                new int[]{5, 3, 5, 0, 5},
                new long[]{5}, // bind var value
                ir(
                        insn(VAR, I4_TYPE, 0, 0),
                        insn(MEM, I4_TYPE, 0, 0),
                        insn(EQ, 0, 0, 0),
                        insn(RET, 0, 0, 0)
                ), SCALAR_OPTIONS, new long[]{0, 2, 4}
        );
    }

    // ========================
    // Count-only mode
    // ========================

    @Test
    public void testCountOnlyIntGt() throws Exception {
        // col0 > 5, count-only: data [3,7,5,10,1,6] → 3 matches (7, 10, 6)
        int[] data = {3, 7, 5, 10, 1, 6};
        IrDecoder.Instruction[] instructions = ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );

        long colData = allocIntColumn(data);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        Unsafe.getUnsafe().putLong(colPtrArray, colData);

        try {
            LoweredProgram prog = IrLowering.lower(instructions, SCALAR_OPTIONS);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);

            long count = filter.countRows(colPtrArray, 1, 0, 0, 0, data.length);
            Assert.assertEquals(3, count);
        } finally {
            Unsafe.free(colData, (long) data.length * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
        }
    }

    // ========================
    // Mixed type (int vs float) tests
    // ========================

    @Test
    public void testMixedIntFloatComparison() throws Exception {
        // col0 (I4) > 2.5 (F8) — the serializer promotes I4 to F8
        // IR: IMM F8 2.5, MEM I4 col0, GT, RET
        IrDecoder.Instruction[] instructions = ir(
                new IrDecoder.Instruction(IMM, F8_TYPE, Double.doubleToRawLongBits(2.5), 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );

        // This is a scalar program (mixed sizes), no null checks
        // col0 > 2.5: data [1,3,2,5,0] → rows 1(3), 3(5)
        int options = (3 << 1); // log2(8)=3, scalar hint
        assertIntColResult(new int[]{1, 3, 2, 5, 0}, instructions, options, new long[]{1, 3});
    }

    @Test
    public void testFloatConstantComparison() throws Exception {
        // col0 (F4) > 3.14 (F4)
        IrDecoder.Instruction[] instructions = ir(
                new IrDecoder.Instruction(IMM, F4_TYPE, Double.doubleToRawLongBits(3.14), 0),
                new IrDecoder.Instruction(MEM, F4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );

        int options = (2 << 1) | (1 << 4); // log2(4), single-size
        float[] data = {1.0f, 4.0f, 3.14f, 5.0f, 2.0f};
        long colData = Unsafe.malloc((long) data.length * Float.BYTES, MemoryTag.NATIVE_DEFAULT);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long expectedBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        for (int i = 0; i < data.length; i++) {
            Unsafe.getUnsafe().putFloat(colData + (long) i * Float.BYTES, data[i]);
        }
        Unsafe.getUnsafe().putLong(colPtrArray, colData);

        try {
            // col0 > 3.14: rows 1(4.0), 3(5.0) — 3.14 is epsilon-equal so not GT
            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            Assert.assertNotNull("filter should be supported", filter);
            long actual = filter.filterRows(colPtrArray, 1, 0, 0, 0, outputBuf, data.length);

            Assert.assertEquals("row count", 2, actual);
            Assert.assertEquals("row 0", 1L, Unsafe.getUnsafe().getLong(outputBuf));
            Assert.assertEquals("row 1", 3L, Unsafe.getUnsafe().getLong(outputBuf + 8));
        } finally {
            Unsafe.free(colData, (long) data.length * Float.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(expectedBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        }
    }

    // ========================
    // Byte (I1) type tests
    // ========================

    @Test
    public void testByteEq() throws Exception {
        // col0 == 3 (byte column)
        byte[] data = {3, 1, 3, 2};
        long colData = Unsafe.malloc(data.length, MemoryTag.NATIVE_DEFAULT);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long expectedBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        for (int i = 0; i < data.length; i++) {
            Unsafe.getUnsafe().putByte(colData + i, data[i]);
        }
        Unsafe.getUnsafe().putLong(colPtrArray, colData);

        IrDecoder.Instruction[] instructions = ir(
                insn(IMM, I1_TYPE, 3, 0),
                insn(MEM, I1_TYPE, 0, 0),
                insn(EQ, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );
        int options = (0 << 1) | (1 << 4); // I1 single-size

        try {
            // col0 == 3: rows 0(3), 2(3)
            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            Assert.assertNotNull("filter should be supported", filter);
            long actual = filter.filterRows(colPtrArray, 1, 0, 0, 0, outputBuf, data.length);

            Assert.assertEquals("row count", 2, actual);
            Assert.assertEquals("row 0", 0L, Unsafe.getUnsafe().getLong(outputBuf));
            Assert.assertEquals("row 1", 2L, Unsafe.getUnsafe().getLong(outputBuf + 8));
        } finally {
            Unsafe.free(colData, data.length, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(expectedBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        }
    }

    // ========================
    // Empty and boundary cases
    // ========================

    @Test
    public void testEmptyInput() throws Exception {
        IrDecoder.Instruction[] instructions = ir(
                insn(IMM, I4_TYPE, 5, 0),
                insn(MEM, I4_TYPE, 0, 0),
                insn(GT, 0, 0, 0),
                insn(RET, 0, 0, 0)
        );

        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        try {
            LoweredProgram prog = IrLowering.lower(instructions, SCALAR_OPTIONS);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            long matched = filter.filterRows(colPtrArray, 1, 0, 0, 0, outputBuf, 0);
            Assert.assertEquals(0, matched);
        } finally {
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, 8, MemoryTag.NATIVE_DEFAULT);
        }
    }

    // ========================
    // Helpers
    // ========================

    private void assertIntColResult(int[] data, IrDecoder.Instruction[] instructions, int options, long[] expectedRows) throws Exception {
        long colData = allocIntColumn(data);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        Unsafe.getUnsafe().putLong(colPtrArray, colData);

        try {
            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            long actual = filter.filterRows(colPtrArray, 1, 0, 0, 0, outputBuf, data.length);

            Assert.assertEquals("row count", expectedRows.length, actual);
            for (int i = 0; i < expectedRows.length; i++) {
                Assert.assertEquals("row " + i, expectedRows[i], Unsafe.getUnsafe().getLong(outputBuf + (long) i * 8));
            }
        } finally {
            Unsafe.free(colData, (long) data.length * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        }
    }

    private void assertTwoIntColsResult(int[] data0, int[] data1, IrDecoder.Instruction[] instructions, int options, long[] expectedRows) throws Exception {
        assert data0.length == data1.length;
        int len = data0.length;
        long col0 = allocIntColumn(data0);
        long col1 = allocIntColumn(data1);
        long colPtrArray = Unsafe.malloc(16, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) len * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        Unsafe.getUnsafe().putLong(colPtrArray, col0);
        Unsafe.getUnsafe().putLong(colPtrArray + 8, col1);

        try {
            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            long actual = filter.filterRows(colPtrArray, 2, 0, 0, 0, outputBuf, len);

            Assert.assertEquals("row count", expectedRows.length, actual);
            for (int i = 0; i < expectedRows.length; i++) {
                Assert.assertEquals("row " + i, expectedRows[i], Unsafe.getUnsafe().getLong(outputBuf + (long) i * 8));
            }
        } finally {
            Unsafe.free(col0, (long) len * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(col1, (long) len * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 16, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) len * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        }
    }

    private void assertIntColWithVarResult(int[] data, long[] varValues, IrDecoder.Instruction[] instructions, int options, long[] expectedRows) throws Exception {
        long colData = allocIntColumn(data);
        long colPtrArray = Unsafe.malloc(8, MemoryTag.NATIVE_DEFAULT);
        long outputBuf = Unsafe.malloc((long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
        long varsMem = Unsafe.malloc((long) varValues.length * 8, MemoryTag.NATIVE_DEFAULT);
        Unsafe.getUnsafe().putLong(colPtrArray, colData);
        for (int i = 0; i < varValues.length; i++) {
            Unsafe.getUnsafe().putLong(varsMem + (long) i * 8, varValues[i]);
        }

        try {
            LoweredProgram prog = IrLowering.lower(instructions, options);
            ScalarBytecodeFilterCompiler.ScalarFilterBody filter = ScalarBytecodeFilterCompiler.compile(prog);
            long actual = filter.filterRows(colPtrArray, 1, 0, varsMem, varValues.length, outputBuf, data.length);

            Assert.assertEquals("row count", expectedRows.length, actual);
            for (int i = 0; i < expectedRows.length; i++) {
                Assert.assertEquals("row " + i, expectedRows[i], Unsafe.getUnsafe().getLong(outputBuf + (long) i * 8));
            }
        } finally {
            Unsafe.free(colData, (long) data.length * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(colPtrArray, 8, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(outputBuf, (long) data.length * Long.BYTES, MemoryTag.NATIVE_DEFAULT);
            Unsafe.free(varsMem, (long) varValues.length * 8, MemoryTag.NATIVE_DEFAULT);
        }
    }

    private static long allocIntColumn(int[] data) {
        long mem = Unsafe.malloc((long) data.length * Integer.BYTES, MemoryTag.NATIVE_DEFAULT);
        for (int i = 0; i < data.length; i++) {
            Unsafe.getUnsafe().putInt(mem + (long) i * Integer.BYTES, data[i]);
        }
        return mem;
    }

    private static IrDecoder.Instruction[] ir(IrDecoder.Instruction... instructions) {
        return instructions;
    }

    private static IrDecoder.Instruction insn(int opcode, int type, long lo, long hi) {
        return new IrDecoder.Instruction(opcode, type, lo, hi);
    }
}
