/*******************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.jit;

import io.questdb.std.Numbers;
import io.questdb.std.Unsafe;

import static io.questdb.jit.CompiledFilterIRSerializer.*;

/**
 * Static helper methods called by bytecode-generated JIT filter classes.
 * These keep the generated bytecode compact and delegate complex operations
 * (Unsafe memory access, float epsilon comparison, null checks) to handwritten Java.
 */
public final class FilterHelpers {
    private static final double DOUBLE_EPSILON = 1e-10;
    private static final float FLOAT_EPSILON = 1e-10f;
    private static final sun.misc.Unsafe UNSAFE = Unsafe.getUnsafe();

    /**
     * Pre-computed iota array for vectorized row-ID generation.
     * Used by VectorBytecodeFilterCompiler to create the iota vector
     * without per-call allocation. Sized for the largest possible
     * vector species (AVX-512 = 64 byte lanes = 8 long lanes).
     */
    public static final long[] IOTA_LONG = {
            0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
            16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
            32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
            48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63
    };

    /**
     * A single MemorySegment covering the entire native address space.
     * Used as the segment argument for all fromMemorySegment/intoMemorySegment
     * calls, with raw addresses passed as offsets. Being a static final field,
     * C2 constant-folds the segment metadata (length, scope), eliminating
     * per-iteration scope/bounds checks from the hot loop.
     */
    public static final java.lang.foreign.MemorySegment UNIVERSE =
            java.lang.foreign.MemorySegment.ofAddress(0).reinterpret(Long.MAX_VALUE);

    // --- Vector API helpers (called by generated vectorized filter classes) ---

    /**
     * Reads the raw column data address from the data pointer array.
     */
    public static long columnAddress(long dataAddress, int columnIndex) {
        return UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
    }

    /**
     * Creates a MemorySegment for a column's data, reading the column address
     * from the data pointer array.
     */
    public static java.lang.foreign.MemorySegment columnSegment(long dataAddress, int columnIndex) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return java.lang.foreign.MemorySegment.NULL;
        }
        return java.lang.foreign.MemorySegment.ofAddress(colAddr).reinterpret(Long.MAX_VALUE);
    }

    /**
     * Creates a MemorySegment wrapping a raw address with maximum size.
     */
    public static java.lang.foreign.MemorySegment segment(long address) {
        return java.lang.foreign.MemorySegment.ofAddress(address).reinterpret(Long.MAX_VALUE);
    }

    /**
     * Returns the native byte order. Called once at method entry, stored in a local.
     */
    public static java.nio.ByteOrder nativeByteOrder() {
        return java.nio.ByteOrder.nativeOrder();
    }

    /**
     * Returns the preferred LongVector species. Called once at method entry.
     */
    public static jdk.incubator.vector.VectorSpecies<Long> longSpecies() {
        return jdk.incubator.vector.LongVector.SPECIES_PREFERRED;
    }

    /**
     * Returns the preferred DoubleVector species. Called once at method entry.
     */
    public static jdk.incubator.vector.VectorSpecies<Double> doubleSpecies() {
        return jdk.incubator.vector.DoubleVector.SPECIES_PREFERRED;
    }

    /**
     * Returns an IntVector species whose lane count matches the preferred
     * LongVector lane count. This lets mixed I8/I4 programs keep a single
     * row stride while using a narrower vector shape for ints.
     */
    public static jdk.incubator.vector.VectorSpecies<Integer> intSpeciesForLongRows() {
        return jdk.incubator.vector.VectorSpecies.of(
                int.class,
                jdk.incubator.vector.VectorShape.forBitSize(
                        jdk.incubator.vector.LongVector.SPECIES_PREFERRED.length() * Integer.SIZE
                )
        );
    }

    /**
     * Returns a FloatVector species whose lane count matches the preferred
     * LongVector lane count. This lets mixed F4 programs keep a single
     * row stride while using a narrower vector shape for floats.
     */
    public static jdk.incubator.vector.VectorSpecies<Float> floatSpeciesForLongRows() {
        return jdk.incubator.vector.VectorSpecies.of(
                float.class,
                jdk.incubator.vector.VectorShape.forBitSize(
                        jdk.incubator.vector.LongVector.SPECIES_PREFERRED.length() * Float.SIZE
                )
        );
    }

    /**
     * Returns a ByteVector species whose lane count matches the preferred
     * LongVector lane count. Used transiently for loading byte columns
     * before widening to IntVector.
     */
    public static jdk.incubator.vector.VectorSpecies<Byte> byteSpeciesForLongRows() {
        return jdk.incubator.vector.VectorSpecies.of(
                byte.class,
                jdk.incubator.vector.VectorShape.forBitSize(
                        jdk.incubator.vector.LongVector.SPECIES_PREFERRED.length() * Byte.SIZE
                )
        );
    }

    /**
     * Returns a ShortVector species whose lane count matches the preferred
     * LongVector lane count. Used transiently for loading short columns
     * before widening to IntVector.
     */
    public static jdk.incubator.vector.VectorSpecies<Short> shortSpeciesForLongRows() {
        return jdk.incubator.vector.VectorSpecies.of(
                short.class,
                jdk.incubator.vector.VectorShape.forBitSize(
                        jdk.incubator.vector.LongVector.SPECIES_PREFERRED.length() * Short.SIZE
                )
        );
    }

    /**
     * Creates the iota LongVector [0, 1, 2, ..., species.length()-1].
     * Called once at method entry for row-ID mode.
     */
    public static jdk.incubator.vector.LongVector iotaVector(jdk.incubator.vector.VectorSpecies<Long> species) {
        return jdk.incubator.vector.LongVector.fromArray(species, IOTA_LONG, 0);
    }

    /**
     * Returns a LongVector with all lanes set to LONG_NULL sentinel.
     */
    public static jdk.incubator.vector.LongVector longNullVector(jdk.incubator.vector.VectorSpecies<Long> species) {
        return jdk.incubator.vector.LongVector.broadcast(species, io.questdb.std.Numbers.LONG_NULL);
    }

    /**
     * Returns a DoubleVector with all lanes set to NaN (double null sentinel).
     */
    public static jdk.incubator.vector.DoubleVector doubleNanVector(jdk.incubator.vector.VectorSpecies<Double> species) {
        return jdk.incubator.vector.DoubleVector.broadcast(species, Double.NaN);
    }

    // --- Vectorized null-aware comparisons ---

    public static jdk.incubator.vector.VectorMask<Long> longNullLt(
            jdk.incubator.vector.LongVector lhs,
            jdk.incubator.vector.LongVector rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        jdk.incubator.vector.VectorMask<Long> anyNull = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec)
                .or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec));
        return lhs.compare(jdk.incubator.vector.VectorOperators.LT, rhs).and(anyNull.not());
    }

    public static jdk.incubator.vector.VectorMask<Long> longNullLe(
            jdk.incubator.vector.LongVector lhs,
            jdk.incubator.vector.LongVector rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        jdk.incubator.vector.VectorMask<Long> lhsNull = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        jdk.incubator.vector.VectorMask<Long> rhsNull = rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        jdk.incubator.vector.VectorMask<Long> anyNull = lhsNull.or(rhsNull);
        jdk.incubator.vector.VectorMask<Long> bothNull = lhsNull.and(rhsNull);
        return lhs.compare(jdk.incubator.vector.VectorOperators.LE, rhs).and(anyNull.not()).or(bothNull);
    }

    public static jdk.incubator.vector.VectorMask<Long> longNullGt(
            jdk.incubator.vector.LongVector lhs,
            jdk.incubator.vector.LongVector rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        jdk.incubator.vector.VectorMask<Long> anyNull = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec)
                .or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec));
        return lhs.compare(jdk.incubator.vector.VectorOperators.GT, rhs).and(anyNull.not());
    }

    public static jdk.incubator.vector.VectorMask<Long> longNullGe(
            jdk.incubator.vector.LongVector lhs,
            jdk.incubator.vector.LongVector rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        jdk.incubator.vector.VectorMask<Long> lhsNull = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        jdk.incubator.vector.VectorMask<Long> rhsNull = rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        jdk.incubator.vector.VectorMask<Long> anyNull = lhsNull.or(rhsNull);
        jdk.incubator.vector.VectorMask<Long> bothNull = lhsNull.and(rhsNull);
        return lhs.compare(jdk.incubator.vector.VectorOperators.GE, rhs).and(anyNull.not()).or(bothNull);
    }

    public static jdk.incubator.vector.VectorMask<Integer> intVecNullEq(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        return lhs.compare(jdk.incubator.vector.VectorOperators.EQ, rhs);
    }

    public static jdk.incubator.vector.VectorMask<Integer> intVecNullNe(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        return lhs.compare(jdk.incubator.vector.VectorOperators.NE, rhs);
    }

    @SuppressWarnings("unchecked")
    public static jdk.incubator.vector.VectorMask<Integer> intVecNullLt(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        jdk.incubator.vector.IntVector nullVec = jdk.incubator.vector.IntVector.broadcast(
                (jdk.incubator.vector.VectorSpecies<Integer>) lhs.species(),
                Numbers.INT_NULL
        );
        jdk.incubator.vector.VectorMask<Integer> anyNull = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec)
                .or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec));
        return lhs.compare(jdk.incubator.vector.VectorOperators.LT, rhs).and(anyNull.not());
    }

    @SuppressWarnings("unchecked")
    public static jdk.incubator.vector.VectorMask<Integer> intVecNullLe(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        jdk.incubator.vector.IntVector nullVec = jdk.incubator.vector.IntVector.broadcast(
                (jdk.incubator.vector.VectorSpecies<Integer>) lhs.species(),
                Numbers.INT_NULL
        );
        jdk.incubator.vector.VectorMask<Integer> lhsNull = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        jdk.incubator.vector.VectorMask<Integer> rhsNull = rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        jdk.incubator.vector.VectorMask<Integer> anyNull = lhsNull.or(rhsNull);
        jdk.incubator.vector.VectorMask<Integer> bothNull = lhsNull.and(rhsNull);
        return lhs.compare(jdk.incubator.vector.VectorOperators.LE, rhs).and(anyNull.not()).or(bothNull);
    }

    @SuppressWarnings("unchecked")
    public static jdk.incubator.vector.VectorMask<Integer> intVecNullGt(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        jdk.incubator.vector.IntVector nullVec = jdk.incubator.vector.IntVector.broadcast(
                (jdk.incubator.vector.VectorSpecies<Integer>) lhs.species(),
                Numbers.INT_NULL
        );
        jdk.incubator.vector.VectorMask<Integer> anyNull = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec)
                .or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec));
        return lhs.compare(jdk.incubator.vector.VectorOperators.GT, rhs).and(anyNull.not());
    }

    @SuppressWarnings("unchecked")
    public static jdk.incubator.vector.VectorMask<Integer> intVecNullGe(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        jdk.incubator.vector.IntVector nullVec = jdk.incubator.vector.IntVector.broadcast(
                (jdk.incubator.vector.VectorSpecies<Integer>) lhs.species(),
                Numbers.INT_NULL
        );
        jdk.incubator.vector.VectorMask<Integer> lhsNull = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        jdk.incubator.vector.VectorMask<Integer> rhsNull = rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        jdk.incubator.vector.VectorMask<Integer> anyNull = lhsNull.or(rhsNull);
        jdk.incubator.vector.VectorMask<Integer> bothNull = lhsNull.and(rhsNull);
        return lhs.compare(jdk.incubator.vector.VectorOperators.GE, rhs).and(anyNull.not()).or(bothNull);
    }

    // --- Vectorized null-aware arithmetic ---

    /**
     * I8 null-aware arithmetic. Preserves LONG_NULL: if either operand is
     * LONG_NULL, the result is LONG_NULL. Division by zero returns LONG_NULL.
     */
    @SuppressWarnings("unchecked")
    public static jdk.incubator.vector.LongVector longVecAddNull(
            jdk.incubator.vector.LongVector lhs,
            jdk.incubator.vector.LongVector rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        jdk.incubator.vector.VectorMask<Long> invalidMask = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec)
                .or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec));
        return lhs.add(rhs).blend(nullVec, invalidMask);
    }

    public static jdk.incubator.vector.LongVector longVecAddNull(
            jdk.incubator.vector.LongVector lhs,
            long rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        if (rhs == Numbers.LONG_NULL) {
            return nullVec;
        }
        jdk.incubator.vector.VectorMask<Long> invalidMask = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        return lhs.add(rhs).blend(nullVec, invalidMask);
    }

    public static jdk.incubator.vector.LongVector longVecSubNull(
            jdk.incubator.vector.LongVector lhs,
            jdk.incubator.vector.LongVector rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        jdk.incubator.vector.VectorMask<Long> invalidMask = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec)
                .or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec));
        return lhs.sub(rhs).blend(nullVec, invalidMask);
    }

    public static jdk.incubator.vector.LongVector longVecSubNull(
            jdk.incubator.vector.LongVector lhs,
            long rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        if (rhs == Numbers.LONG_NULL) {
            return nullVec;
        }
        jdk.incubator.vector.VectorMask<Long> invalidMask = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        return lhs.sub(rhs).blend(nullVec, invalidMask);
    }

    public static jdk.incubator.vector.LongVector longVecMulNull(
            jdk.incubator.vector.LongVector lhs,
            jdk.incubator.vector.LongVector rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        jdk.incubator.vector.VectorMask<Long> invalidMask = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec)
                .or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec));
        return lhs.mul(rhs).blend(nullVec, invalidMask);
    }

    public static jdk.incubator.vector.LongVector longVecMulNull(
            jdk.incubator.vector.LongVector lhs,
            long rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        if (rhs == Numbers.LONG_NULL) {
            return nullVec;
        }
        jdk.incubator.vector.VectorMask<Long> invalidMask = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        return lhs.mul(rhs).blend(nullVec, invalidMask);
    }

    @SuppressWarnings("unchecked")
    public static jdk.incubator.vector.LongVector longVecDivNull(
            jdk.incubator.vector.LongVector lhs,
            jdk.incubator.vector.LongVector rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        jdk.incubator.vector.VectorMask<Long> invalidMask = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec)
                .or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec));
        jdk.incubator.vector.LongVector zero = jdk.incubator.vector.LongVector.zero(
                (jdk.incubator.vector.VectorSpecies<Long>) lhs.species());
        invalidMask = invalidMask.or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, zero));
        return lhs.div(rhs, invalidMask.not()).blend(nullVec, invalidMask);
    }

    public static jdk.incubator.vector.LongVector longVecDivNull(
            jdk.incubator.vector.LongVector lhs,
            long rhs,
            jdk.incubator.vector.LongVector nullVec
    ) {
        if (rhs == Numbers.LONG_NULL || rhs == 0L) {
            return nullVec;
        }
        jdk.incubator.vector.VectorMask<Long> invalidMask = lhs.compare(jdk.incubator.vector.VectorOperators.EQ, nullVec);
        return lhs.div(rhs).blend(nullVec, invalidMask);
    }

    /**
     * I4 null-aware arithmetic. Preserves INT_NULL: if either operand is
     * INT_NULL, the result is INT_NULL. Division by zero returns INT_NULL.
     */
    public static jdk.incubator.vector.IntVector intVecAddNull(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Integer> invalidMask = lhs.eq(Numbers.INT_NULL)
                .or(rhs.eq(Numbers.INT_NULL));
        return lhs.add(rhs).blend(Numbers.INT_NULL, invalidMask);
    }

    public static jdk.incubator.vector.IntVector intVecAddNull(
            jdk.incubator.vector.IntVector lhs,
            int rhs
    ) {
        if (rhs == Numbers.INT_NULL) {
            return jdk.incubator.vector.IntVector.broadcast(lhs.species(), Numbers.INT_NULL);
        }
        jdk.incubator.vector.VectorMask<Integer> invalidMask = lhs.eq(Numbers.INT_NULL);
        return lhs.add(rhs).blend(Numbers.INT_NULL, invalidMask);
    }

    public static jdk.incubator.vector.IntVector intVecSubNull(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Integer> invalidMask = lhs.eq(Numbers.INT_NULL)
                .or(rhs.eq(Numbers.INT_NULL));
        return lhs.sub(rhs).blend(Numbers.INT_NULL, invalidMask);
    }

    public static jdk.incubator.vector.IntVector intVecSubNull(
            jdk.incubator.vector.IntVector lhs,
            int rhs
    ) {
        if (rhs == Numbers.INT_NULL) {
            return jdk.incubator.vector.IntVector.broadcast(lhs.species(), Numbers.INT_NULL);
        }
        jdk.incubator.vector.VectorMask<Integer> invalidMask = lhs.eq(Numbers.INT_NULL);
        return lhs.sub(rhs).blend(Numbers.INT_NULL, invalidMask);
    }

    public static jdk.incubator.vector.IntVector intVecMulNull(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Integer> invalidMask = lhs.eq(Numbers.INT_NULL)
                .or(rhs.eq(Numbers.INT_NULL));
        return lhs.mul(rhs).blend(Numbers.INT_NULL, invalidMask);
    }

    public static jdk.incubator.vector.IntVector intVecMulNull(
            jdk.incubator.vector.IntVector lhs,
            int rhs
    ) {
        if (rhs == Numbers.INT_NULL) {
            return jdk.incubator.vector.IntVector.broadcast(lhs.species(), Numbers.INT_NULL);
        }
        jdk.incubator.vector.VectorMask<Integer> invalidMask = lhs.eq(Numbers.INT_NULL);
        return lhs.mul(rhs).blend(Numbers.INT_NULL, invalidMask);
    }

    @SuppressWarnings("unchecked")
    public static jdk.incubator.vector.IntVector intVecDivNull(
            jdk.incubator.vector.IntVector lhs,
            jdk.incubator.vector.IntVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Integer> invalidMask = lhs.eq(Numbers.INT_NULL)
                .or(rhs.eq(Numbers.INT_NULL));
        jdk.incubator.vector.IntVector zero = jdk.incubator.vector.IntVector.zero(
                (jdk.incubator.vector.VectorSpecies<Integer>) lhs.species());
        invalidMask = invalidMask.or(rhs.compare(jdk.incubator.vector.VectorOperators.EQ, zero));
        return lhs.div(rhs, invalidMask.not()).blend(Numbers.INT_NULL, invalidMask);
    }

    public static jdk.incubator.vector.IntVector intVecDivNull(
            jdk.incubator.vector.IntVector lhs,
            int rhs
    ) {
        if (rhs == Numbers.INT_NULL || rhs == 0) {
            return jdk.incubator.vector.IntVector.broadcast(lhs.species(), Numbers.INT_NULL);
        }
        jdk.incubator.vector.VectorMask<Integer> invalidMask = lhs.eq(Numbers.INT_NULL);
        return lhs.div(rhs).blend(Numbers.INT_NULL, invalidMask);
    }

    /**
     * F8 arithmetic with NaN propagation and div-by-zero → NaN.
     * Always used for double arithmetic regardless of null check mode,
     * because QuestDB requires NaN-on-zero-division (not IEEE infinity).
     */
    public static jdk.incubator.vector.DoubleVector doubleVecAdd(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        return lhs.add(rhs);
    }

    public static jdk.incubator.vector.DoubleVector doubleVecAdd(
            jdk.incubator.vector.DoubleVector lhs,
            double rhs
    ) {
        return lhs.add(rhs);
    }

    public static jdk.incubator.vector.DoubleVector doubleVecSub(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        return lhs.sub(rhs);
    }

    public static jdk.incubator.vector.DoubleVector doubleVecSub(
            jdk.incubator.vector.DoubleVector lhs,
            double rhs
    ) {
        return lhs.sub(rhs);
    }

    public static jdk.incubator.vector.DoubleVector doubleVecMul(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        return lhs.mul(rhs);
    }

    public static jdk.incubator.vector.DoubleVector doubleVecMul(
            jdk.incubator.vector.DoubleVector lhs,
            double rhs
    ) {
        return lhs.mul(rhs);
    }

    public static jdk.incubator.vector.DoubleVector doubleVecDiv(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Double> zeroDiv = rhs.compare(
                jdk.incubator.vector.VectorOperators.EQ, 0.0);
        return lhs.div(rhs, zeroDiv.not()).blend(Double.NaN, zeroDiv);
    }

    public static jdk.incubator.vector.DoubleVector doubleVecDiv(
            jdk.incubator.vector.DoubleVector lhs,
            double rhs
    ) {
        if (rhs == 0.0d) {
            return jdk.incubator.vector.DoubleVector.broadcast(lhs.species(), Double.NaN);
        }
        return lhs.div(rhs);
    }

    // --- Vectorized double comparisons (epsilon + NaN-aware) ---
    // QuestDB float/double semantics:
    // - EQ: |a-b| <= EPSILON, NaN == NaN → true
    // - NE: |a-b| > EPSILON, NaN != non-NaN → true
    // - GT: a > b AND NOT epsilon-equal, false if either is NaN
    // - GE: a >= b OR epsilon-equal, true if both are NaN
    // - LT: a < b AND NOT epsilon-equal, false if either is NaN
    // - LE: a <= b OR epsilon-equal, true if both are NaN

    private static final double VEC_DOUBLE_EPSILON = DOUBLE_EPSILON;

    public static jdk.incubator.vector.VectorMask<Double> doubleVecEq(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Double> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> rhsNaN = rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> bothNaN = lhsNaN.and(rhsNaN);
        jdk.incubator.vector.VectorMask<Double> anyNaN = lhsNaN.or(rhsNaN);
        // Epsilon equality on non-NaN lanes, plus both-NaN
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, anyNaN.not());
        return epsilonEq.or(bothNaN);
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecNe(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        return doubleVecEq(lhs, rhs).not();
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecLt(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Double> anyNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN)
                .or(rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN));
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, anyNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.LT, rhs, anyNaN.not()).and(epsilonEq.not());
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecLe(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Double> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> rhsNaN = rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> bothNaN = lhsNaN.and(rhsNaN);
        jdk.incubator.vector.VectorMask<Double> anyNaN = lhsNaN.or(rhsNaN);
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, anyNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.LE, rhs, anyNaN.not()).or(epsilonEq).or(bothNaN);
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecGt(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Double> anyNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN)
                .or(rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN));
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, anyNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.GT, rhs, anyNaN.not()).and(epsilonEq.not());
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecGe(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Double> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> rhsNaN = rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> bothNaN = lhsNaN.and(rhsNaN);
        jdk.incubator.vector.VectorMask<Double> anyNaN = lhsNaN.or(rhsNaN);
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, anyNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.GE, rhs, anyNaN.not()).or(epsilonEq).or(bothNaN);
    }

    // --- Specialized epsilon helpers when RHS is a known non-NaN constant ---
    // These skip the RHS NaN test, eliminating 3 dead mask operations that
    // C2 fails to constant-fold (see Phase 12 of jit-assembly-quality-investigation).

    public static jdk.incubator.vector.VectorMask<Double> doubleVecEqRhsFinite(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        // rhsNaN = false, bothNaN = false, anyNaN = lhsNaN
        jdk.incubator.vector.VectorMask<Double> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, lhsNaN.not());
        return epsilonEq; // bothNaN is always false, so no .or(bothNaN)
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecNeRhsFinite(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        return doubleVecEqRhsFinite(lhs, rhs).not();
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecLtRhsFinite(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Double> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, lhsNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.LT, rhs, lhsNaN.not()).and(epsilonEq.not());
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecLeRhsFinite(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        // rhsNaN = false, bothNaN = false, anyNaN = lhsNaN
        jdk.incubator.vector.VectorMask<Double> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, lhsNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.LE, rhs, lhsNaN.not()).or(epsilonEq);
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecGtRhsFinite(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Double> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, lhsNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.GT, rhs, lhsNaN.not()).and(epsilonEq.not());
    }

    public static jdk.incubator.vector.VectorMask<Double> doubleVecGeRhsFinite(
            jdk.incubator.vector.DoubleVector lhs,
            jdk.incubator.vector.DoubleVector rhs
    ) {
        // rhsNaN = false, bothNaN = false, anyNaN = lhsNaN
        jdk.incubator.vector.VectorMask<Double> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Double> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_DOUBLE_EPSILON, lhsNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.GE, rhs, lhsNaN.not()).or(epsilonEq);
    }

    // --- Vectorized float arithmetic (NaN + div-by-zero) ---

    /**
     * F4 arithmetic with NaN propagation and div-by-zero → NaN.
     */
    public static jdk.incubator.vector.FloatVector floatVecAdd(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        return lhs.add(rhs);
    }

    public static jdk.incubator.vector.FloatVector floatVecAdd(
            jdk.incubator.vector.FloatVector lhs,
            float rhs
    ) {
        return lhs.add(rhs);
    }

    public static jdk.incubator.vector.FloatVector floatVecSub(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        return lhs.sub(rhs);
    }

    public static jdk.incubator.vector.FloatVector floatVecSub(
            jdk.incubator.vector.FloatVector lhs,
            float rhs
    ) {
        return lhs.sub(rhs);
    }

    public static jdk.incubator.vector.FloatVector floatVecMul(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        return lhs.mul(rhs);
    }

    public static jdk.incubator.vector.FloatVector floatVecMul(
            jdk.incubator.vector.FloatVector lhs,
            float rhs
    ) {
        return lhs.mul(rhs);
    }

    public static jdk.incubator.vector.FloatVector floatVecDiv(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> zeroDiv = rhs.compare(
                jdk.incubator.vector.VectorOperators.EQ, 0.0f);
        return lhs.div(rhs, zeroDiv.not()).blend(Float.NaN, zeroDiv);
    }

    public static jdk.incubator.vector.FloatVector floatVecDiv(
            jdk.incubator.vector.FloatVector lhs,
            float rhs
    ) {
        if (rhs == 0.0f) {
            return jdk.incubator.vector.FloatVector.broadcast(lhs.species(), Float.NaN);
        }
        return lhs.div(rhs);
    }

    // --- Vectorized float comparisons (epsilon + NaN-aware) ---

    private static final float VEC_FLOAT_EPSILON = FLOAT_EPSILON;

    public static jdk.incubator.vector.VectorMask<Float> floatVecEq(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> rhsNaN = rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> bothNaN = lhsNaN.and(rhsNaN);
        jdk.incubator.vector.VectorMask<Float> anyNaN = lhsNaN.or(rhsNaN);
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, anyNaN.not());
        return epsilonEq.or(bothNaN);
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecNe(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        return floatVecEq(lhs, rhs).not();
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecLt(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> anyNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN)
                .or(rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN));
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, anyNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.LT, rhs, anyNaN.not()).and(epsilonEq.not());
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecLe(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> rhsNaN = rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> bothNaN = lhsNaN.and(rhsNaN);
        jdk.incubator.vector.VectorMask<Float> anyNaN = lhsNaN.or(rhsNaN);
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, anyNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.LE, rhs, anyNaN.not()).or(epsilonEq).or(bothNaN);
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecGt(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> anyNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN)
                .or(rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN));
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, anyNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.GT, rhs, anyNaN.not()).and(epsilonEq.not());
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecGe(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> rhsNaN = rhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> bothNaN = lhsNaN.and(rhsNaN);
        jdk.incubator.vector.VectorMask<Float> anyNaN = lhsNaN.or(rhsNaN);
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, anyNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.GE, rhs, anyNaN.not()).or(epsilonEq).or(bothNaN);
    }

    // --- Specialized float epsilon helpers when RHS is a known non-NaN constant ---

    public static jdk.incubator.vector.VectorMask<Float> floatVecEqRhsFinite(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, lhsNaN.not());
        return epsilonEq;
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecNeRhsFinite(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        return floatVecEqRhsFinite(lhs, rhs).not();
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecLtRhsFinite(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, lhsNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.LT, rhs, lhsNaN.not()).and(epsilonEq.not());
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecLeRhsFinite(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, lhsNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.LE, rhs, lhsNaN.not()).or(epsilonEq);
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecGtRhsFinite(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, lhsNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.GT, rhs, lhsNaN.not()).and(epsilonEq.not());
    }

    public static jdk.incubator.vector.VectorMask<Float> floatVecGeRhsFinite(
            jdk.incubator.vector.FloatVector lhs,
            jdk.incubator.vector.FloatVector rhs
    ) {
        jdk.incubator.vector.VectorMask<Float> lhsNaN = lhs.test(jdk.incubator.vector.VectorOperators.IS_NAN);
        jdk.incubator.vector.VectorMask<Float> epsilonEq = lhs.sub(rhs).abs()
                .compare(jdk.incubator.vector.VectorOperators.LE, VEC_FLOAT_EPSILON, lhsNaN.not());
        return lhs.compare(jdk.incubator.vector.VectorOperators.GE, rhs, lhsNaN.not()).or(epsilonEq);
    }

    // --- Column reads ---

    public static byte readByte(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return 0;
        }
        return UNSAFE.getByte(colAddr + row);
    }

    public static double readDouble(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Double.NaN;
        }
        return UNSAFE.getDouble(colAddr + (row << 3));
    }

    public static float readFloat(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Float.NaN;
        }
        return UNSAFE.getFloat(colAddr + (row << 2));
    }

    public static int readInt(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Numbers.INT_NULL;
        }
        return UNSAFE.getInt(colAddr + (row << 2));
    }

    public static long readLong(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Numbers.LONG_NULL;
        }
        return UNSAFE.getLong(colAddr + (row << 3));
    }

    public static long readLong128Hi(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Numbers.LONG_NULL;
        }
        return UNSAFE.getLong(colAddr + (row << 4) + Long.BYTES);
    }

    public static long readLong128Lo(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Numbers.LONG_NULL;
        }
        return UNSAFE.getLong(colAddr + (row << 4));
    }

    public static short readShort(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return 0;
        }
        return UNSAFE.getShort(colAddr + (row << 1));
    }

    // --- Var-size header reads ---

    public static long readBinaryHeader(long dataAddress, long varSizeAuxAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return -1L;
        }
        long auxAddr = UNSAFE.getLong(varSizeAuxAddress + ((long) columnIndex << 3));
        long dataOffset = UNSAFE.getLong(auxAddr + (row << 3));
        return UNSAFE.getLong(colAddr + dataOffset);
    }

    public static int readStringHeader(long dataAddress, long varSizeAuxAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return -1;
        }
        long auxAddr = UNSAFE.getLong(varSizeAuxAddress + ((long) columnIndex << 3));
        long dataOffset = UNSAFE.getLong(auxAddr + (row << 3));
        return UNSAFE.getInt(colAddr + dataOffset);
    }

    public static long readVarcharHeader(long varSizeAuxAddress, int columnIndex, long row) {
        long auxAddr = UNSAFE.getLong(varSizeAuxAddress + ((long) columnIndex << 3));
        if (auxAddr == 0) {
            return 4L; // VARCHAR_HEADER_FLAG_NULL
        }
        return UNSAFE.getLong(auxAddr + (row << 4));
    }

    // --- Vectorized var-size header gathers ---
    // These gather scalar headers into a vector for subsequent NULL check comparison.
    // The int[]/long[] allocations are scalar-replaced by C2 escape analysis.
    // The rowCount parameter limits reads to valid rows in the tail (partial
    // last vector chunk). Without this bound, the gather reads past the end of
    // mapped aux memory, causing a SIGSEGV on page-frame boundaries.

    public static jdk.incubator.vector.IntVector gatherStringHeaders(
            long dataAddress, long varSizeAuxAddress, int columnIndex, long startRow, int rowCount,
            jdk.incubator.vector.VectorSpecies<Integer> species
    ) {
        int[] buf = new int[species.length()];
        int limit = Math.min(rowCount, buf.length);
        for (int i = 0; i < limit; i++) {
            buf[i] = readStringHeader(dataAddress, varSizeAuxAddress, columnIndex, startRow + i);
        }
        return jdk.incubator.vector.IntVector.fromArray(species, buf, 0);
    }

    public static jdk.incubator.vector.LongVector gatherBinaryHeaders(
            long dataAddress, long varSizeAuxAddress, int columnIndex, long startRow, int rowCount,
            jdk.incubator.vector.VectorSpecies<Long> species
    ) {
        long[] buf = new long[species.length()];
        int limit = Math.min(rowCount, buf.length);
        for (int i = 0; i < limit; i++) {
            buf[i] = readBinaryHeader(dataAddress, varSizeAuxAddress, columnIndex, startRow + i);
        }
        return jdk.incubator.vector.LongVector.fromArray(species, buf, 0);
    }

    public static jdk.incubator.vector.LongVector gatherVarcharHeaders(
            long varSizeAuxAddress, int columnIndex, long startRow, int rowCount,
            jdk.incubator.vector.VectorSpecies<Long> species
    ) {
        long[] buf = new long[species.length()];
        int limit = Math.min(rowCount, buf.length);
        for (int i = 0; i < limit; i++) {
            buf[i] = readVarcharHeader(varSizeAuxAddress, columnIndex, startRow + i);
        }
        return jdk.incubator.vector.LongVector.fromArray(species, buf, 0);
    }

    // --- Vectorized I128 (UUID) comparison ---

    /**
     * Compares a UUID column against an immediate UUID value across a chunk of rows.
     * Returns a bitmask where bit i is set if row (startRow+i) matches.
     * The caller converts this to VectorMask via VectorMask.fromLong().
     */
    public static long i128CompareColumnImm(
            long dataAddress, int colIdx, long startRow, int count,
            long immLo, long immHi, int opcode
    ) {
        long bits = 0;
        long colAddr = UNSAFE.getLong(dataAddress + ((long) colIdx << 3));
        for (int i = 0; i < count; i++) {
            long lo, hi;
            if (colAddr == 0) {
                lo = Numbers.LONG_NULL;
                hi = Numbers.LONG_NULL;
            } else {
                long offset = (startRow + i) << 4;
                lo = UNSAFE.getLong(colAddr + offset);
                hi = UNSAFE.getLong(colAddr + offset + 8);
            }
            boolean match = (opcode == EQ)
                    ? (lo == immLo && hi == immHi)
                    : (lo != immLo || hi != immHi);
            if (match) {
                bits |= (1L << i);
            }
        }
        return bits;
    }

    /**
     * Compares a UUID column against a bind variable UUID value.
     */
    public static long i128CompareColumnVar(
            long dataAddress, int colIdx, long startRow, int count,
            long varsAddress, int varByteOffset, int opcode
    ) {
        long immLo = UNSAFE.getLong(varsAddress + varByteOffset);
        long immHi = UNSAFE.getLong(varsAddress + varByteOffset + 8);
        return i128CompareColumnImm(dataAddress, colIdx, startRow, count, immLo, immHi, opcode);
    }

    /**
     * Compares two UUID columns.
     */
    public static long i128CompareColumns(
            long dataAddress, int colIdx1, int colIdx2, long startRow, int count,
            int opcode
    ) {
        long bits = 0;
        long colAddr1 = UNSAFE.getLong(dataAddress + ((long) colIdx1 << 3));
        long colAddr2 = UNSAFE.getLong(dataAddress + ((long) colIdx2 << 3));
        for (int i = 0; i < count; i++) {
            long lo1, hi1, lo2, hi2;
            if (colAddr1 == 0) { lo1 = Numbers.LONG_NULL; hi1 = Numbers.LONG_NULL; } else {
                long off = (startRow + i) << 4;
                lo1 = UNSAFE.getLong(colAddr1 + off);
                hi1 = UNSAFE.getLong(colAddr1 + off + 8);
            }
            if (colAddr2 == 0) { lo2 = Numbers.LONG_NULL; hi2 = Numbers.LONG_NULL; } else {
                long off = (startRow + i) << 4;
                lo2 = UNSAFE.getLong(colAddr2 + off);
                hi2 = UNSAFE.getLong(colAddr2 + off + 8);
            }
            boolean match = (opcode == EQ)
                    ? (lo1 == lo2 && hi1 == hi2)
                    : (lo1 != lo2 || hi1 != hi2);
            if (match) bits |= (1L << i);
        }
        return bits;
    }

    // --- Bind variable reads ---

    public static byte readVarByte(long varsAddress, int byteOffset) {
        return UNSAFE.getByte(varsAddress + byteOffset);
    }

    public static double readVarDouble(long varsAddress, int byteOffset) {
        return UNSAFE.getDouble(varsAddress + byteOffset);
    }

    public static float readVarFloat(long varsAddress, int byteOffset) {
        return UNSAFE.getFloat(varsAddress + byteOffset);
    }

    public static int readVarInt(long varsAddress, int byteOffset) {
        return UNSAFE.getInt(varsAddress + byteOffset);
    }

    public static long readVarLong(long varsAddress, int byteOffset) {
        return UNSAFE.getLong(varsAddress + byteOffset);
    }

    public static short readVarShort(long varsAddress, int byteOffset) {
        return UNSAFE.getShort(varsAddress + byteOffset);
    }

    public static long readVarLong128Hi(long varsAddress, int byteOffset) {
        return UNSAFE.getLong(varsAddress + byteOffset + Long.BYTES);
    }

    // --- Null-aware casts ---

    public static jdk.incubator.vector.DoubleVector longToDoubleNullAware(
            jdk.incubator.vector.LongVector src,
            jdk.incubator.vector.LongVector nullVec
    ) {
        // Detect LONG_NULL lanes
        jdk.incubator.vector.VectorMask<Long> isNull = src.eq(nullVec);
        // Convert L2D
        jdk.incubator.vector.DoubleVector converted = (jdk.incubator.vector.DoubleVector)
                src.convertShape(jdk.incubator.vector.VectorOperators.L2D,
                        jdk.incubator.vector.DoubleVector.SPECIES_PREFERRED, 0);
        // Replace null lanes with NaN
        return converted.blend(Double.NaN, isNull.cast(jdk.incubator.vector.DoubleVector.SPECIES_PREFERRED));
    }

    public static jdk.incubator.vector.DoubleVector intToDoubleNullAware(
            jdk.incubator.vector.IntVector src,
            jdk.incubator.vector.VectorSpecies<Double> doubleSpecies
    ) {
        // Detect INT_NULL lanes before conversion
        jdk.incubator.vector.VectorMask<Integer> isNull = src.eq(Numbers.INT_NULL);
        // Convert I2D
        jdk.incubator.vector.DoubleVector converted = (jdk.incubator.vector.DoubleVector)
                src.convertShape(jdk.incubator.vector.VectorOperators.I2D, doubleSpecies, 0);
        // Replace null lanes with NaN
        return converted.blend(Double.NaN, isNull.cast(doubleSpecies));
    }

    public static jdk.incubator.vector.LongVector intToLongNullAware(
            jdk.incubator.vector.IntVector src,
            jdk.incubator.vector.LongVector nullVec
    ) {
        // Detect INT_NULL lanes before conversion
        jdk.incubator.vector.VectorMask<Integer> isNull = src.eq(Numbers.INT_NULL);
        // Convert I2L — INT_NULL sign-extends to 0xFFFFFFFF80000000, not LONG_NULL
        jdk.incubator.vector.LongVector converted = (jdk.incubator.vector.LongVector)
                src.convertShape(jdk.incubator.vector.VectorOperators.I2L,
                        nullVec.species(), 0);
        // Replace sign-extended null lanes with LONG_NULL
        return converted.blend(nullVec, isNull.cast(nullVec.species()));
    }

    public static jdk.incubator.vector.FloatVector intToFloatNullAware(
            jdk.incubator.vector.IntVector src,
            jdk.incubator.vector.VectorSpecies<Float> floatSpecies
    ) {
        // Detect INT_NULL lanes
        jdk.incubator.vector.VectorMask<Integer> isNull = src.eq(Numbers.INT_NULL);
        // Convert I2F
        jdk.incubator.vector.FloatVector converted = (jdk.incubator.vector.FloatVector)
                src.convertShape(jdk.incubator.vector.VectorOperators.I2F, floatSpecies, 0);
        // Replace null lanes with NaN
        return converted.blend(Float.NaN, isNull.cast(floatSpecies));
    }

    // --- Output writes ---

    public static void writeCompressedRows(
            jdk.incubator.vector.LongVector compressed,
            int matchCount,
            java.lang.foreign.MemorySegment output,
            long byteOffset,
            java.nio.ByteOrder order
    ) {
        jdk.incubator.vector.VectorMask<Long> storeMask =
                compressed.species().indexInRange(0, matchCount);
        compressed.intoMemorySegment(output, byteOffset, order, storeMask);
    }

    /**
     * Writes compressed row IDs to native memory via UNIVERSE segment.
     * Uses absolute address (outputAddr + byteOffset) as the segment offset.
     */
    public static void writeCompressedRowsAbs(
            jdk.incubator.vector.LongVector compressed,
            int matchCount,
            long absoluteByteOffset,
            java.nio.ByteOrder order
    ) {
        jdk.incubator.vector.VectorMask<Long> storeMask =
                compressed.species().indexInRange(0, matchCount);
        compressed.intoMemorySegment(UNIVERSE, absoluteByteOffset, order, storeMask);
    }

    public static void writeRow(long filteredRowsAddress, long outputIndex, long row) {
        UNSAFE.putLong(filteredRowsAddress + (outputIndex << 3), row);
    }

    // --- Float comparisons with epsilon ---

    public static boolean doubleEq(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= DOUBLE_EPSILON;
    }

    public static boolean doubleGe(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= DOUBLE_EPSILON || a >= b;
    }

    public static boolean doubleGt(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return false;
        }
        return Math.abs(a - b) > DOUBLE_EPSILON && a > b;
    }

    public static boolean doubleLe(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= DOUBLE_EPSILON || a <= b;
    }

    public static boolean doubleLt(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return false;
        }
        return Math.abs(a - b) > DOUBLE_EPSILON && a < b;
    }

    public static boolean doubleNe(double a, double b) {
        return !doubleEq(a, b);
    }

    public static boolean floatEq(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= FLOAT_EPSILON;
    }

    public static boolean floatGe(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= FLOAT_EPSILON || a >= b;
    }

    public static boolean floatGt(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return false;
        }
        return Math.abs(a - b) > FLOAT_EPSILON && a > b;
    }

    public static boolean floatLe(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= FLOAT_EPSILON || a <= b;
    }

    public static boolean floatLt(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return false;
        }
        return Math.abs(a - b) > FLOAT_EPSILON && a < b;
    }

    public static boolean floatNe(float a, float b) {
        return !floatEq(a, b);
    }

    // --- Integer comparisons (full-path: handles both null and non-null) ---

    public static boolean intEq(int a, int b) {
        return a == b;
    }

    public static boolean intGe(int a, int b) {
        return a >= b;
    }

    public static boolean intGt(int a, int b) {
        return a > b;
    }

    public static boolean intLe(int a, int b) {
        return a <= b;
    }

    public static boolean intLt(int a, int b) {
        return a < b;
    }

    public static boolean intNe(int a, int b) {
        return a != b;
    }

    // Null-aware: when at least one operand is INT_NULL
    public static boolean intNullEq(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return a == b;
        }
        return a == b;
    }

    public static boolean intNullGe(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return a == b;
        }
        return a >= b;
    }

    public static boolean intNullGt(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return false;
        }
        return a > b;
    }

    public static boolean intNullLe(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return a == b;
        }
        return a <= b;
    }

    public static boolean intNullLt(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return false;
        }
        return a < b;
    }

    public static boolean intNullNe(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return a != b;
        }
        return a != b;
    }

    // --- Long comparisons ---

    public static boolean longEq(long a, long b) {
        return a == b;
    }

    public static boolean longGe(long a, long b) {
        return a >= b;
    }

    public static boolean longGt(long a, long b) {
        return a > b;
    }

    public static boolean longLe(long a, long b) {
        return a <= b;
    }

    public static boolean longLt(long a, long b) {
        return a < b;
    }

    public static boolean longNe(long a, long b) {
        return a != b;
    }

    // Null-aware long comparisons
    public static boolean longNullEq(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return a == b;
        }
        return a == b;
    }

    public static boolean longNullGe(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return a == b;
        }
        return a >= b;
    }

    public static boolean longNullGt(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return false;
        }
        return a > b;
    }

    public static boolean longNullLe(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return a == b;
        }
        return a <= b;
    }

    public static boolean longNullLt(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return false;
        }
        return a < b;
    }

    public static boolean longNullNe(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return a != b;
        }
        return a != b;
    }

    // --- Null-aware type coercions ---

    public static double coerceIntToDouble(int value) {
        return value == Numbers.INT_NULL ? Double.NaN : (double) value;
    }

    public static float coerceIntToFloat(int value) {
        return value == Numbers.INT_NULL ? Float.NaN : (float) value;
    }

    public static long coerceIntToLong(int value) {
        return value == Numbers.INT_NULL ? Numbers.LONG_NULL : (long) value;
    }

    public static double coerceLongToDouble(long value) {
        return value == Numbers.LONG_NULL ? Double.NaN : (double) value;
    }

    // --- Null-aware arithmetic ---

    public static int intArithmeticNull(int a, int b, int opcode) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL || (opcode == 17 && b == 0)) {
            return Numbers.INT_NULL;
        }
        return switch (opcode) {
            case 14 -> a + b; // ADD
            case 15 -> a - b; // SUB
            case 16 -> a * b; // MUL
            case 17 -> a / b; // DIV
            default -> throw new IllegalArgumentException("unsupported int opcode: " + opcode);
        };
    }

    public static long longArithmeticNull(long a, long b, int opcode) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL || (opcode == 17 && b == 0)) {
            return Numbers.LONG_NULL;
        }
        return switch (opcode) {
            case 14 -> a + b; // ADD
            case 15 -> a - b; // SUB
            case 16 -> a * b; // MUL
            case 17 -> a / b; // DIV
            default -> throw new IllegalArgumentException("unsupported long opcode: " + opcode);
        };
    }

    // --- Float/double division (return NaN on div-by-zero) ---

    public static float floatDiv(float a, float b) {
        if (Float.isNaN(a) || Float.isNaN(b) || b == 0) {
            return Float.NaN;
        }
        return a / b;
    }

    public static double doubleDiv(double a, double b) {
        if (Double.isNaN(a) || Double.isNaN(b) || b == 0) {
            return Double.NaN;
        }
        return a / b;
    }

    // --- Float/double null-aware arithmetic (NaN propagation) ---

    public static float floatArithmeticNull(float a, float b, int opcode) {
        if (Float.isNaN(a) || Float.isNaN(b)) {
            return Float.NaN;
        }
        return switch (opcode) {
            case 14 -> a + b; // ADD
            case 15 -> a - b; // SUB
            case 16 -> a * b; // MUL
            case 17 -> b == 0 ? Float.NaN : a / b; // DIV
            default -> throw new IllegalArgumentException("unsupported float opcode: " + opcode);
        };
    }

    public static double doubleAddNull(double a, double b) {
        if (Double.isNaN(a) || Double.isNaN(b)) return Double.NaN;
        return a + b;
    }

    public static double doubleSubNull(double a, double b) {
        if (Double.isNaN(a) || Double.isNaN(b)) return Double.NaN;
        return a - b;
    }

    public static double doubleMulNull(double a, double b) {
        if (Double.isNaN(a) || Double.isNaN(b)) return Double.NaN;
        return a * b;
    }

    public static double doubleDivNull(double a, double b) {
        if (Double.isNaN(a) || Double.isNaN(b)) return Double.NaN;
        return b == 0 ? Double.NaN : a / b;
    }

    // --- I128 (UUID) comparisons ---

    public static boolean i128Eq(long loA, long hiA, long loB, long hiB) {
        return loA == loB && hiA == hiB;
    }

    public static boolean i128Ne(long loA, long hiA, long loB, long hiB) {
        return loA != loB || hiA != hiB;
    }

    private FilterHelpers() {
    }
}
