/*******************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.jit;

import io.questdb.std.Numbers;
import io.questdb.std.Unsafe;

/**
 * Static helper methods called by bytecode-generated JIT filter classes.
 * These keep the generated bytecode compact and delegate complex operations
 * (Unsafe memory access, float epsilon comparison, null checks) to handwritten Java.
 */
public final class FilterHelpers {
    private static final double DOUBLE_EPSILON = 1e-10;
    private static final float FLOAT_EPSILON = 1e-10f;
    private static final sun.misc.Unsafe UNSAFE = Unsafe.getUnsafe();

    // --- Column reads ---

    public static byte readByte(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return 0;
        }
        return UNSAFE.getByte(colAddr + row);
    }

    public static double readDouble(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Double.NaN;
        }
        return UNSAFE.getDouble(colAddr + (row << 3));
    }

    public static float readFloat(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Float.NaN;
        }
        return UNSAFE.getFloat(colAddr + (row << 2));
    }

    public static int readInt(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Numbers.INT_NULL;
        }
        return UNSAFE.getInt(colAddr + (row << 2));
    }

    public static long readLong(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Numbers.LONG_NULL;
        }
        return UNSAFE.getLong(colAddr + (row << 3));
    }

    public static long readLong128Hi(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Numbers.LONG_NULL;
        }
        return UNSAFE.getLong(colAddr + (row << 4) + Long.BYTES);
    }

    public static long readLong128Lo(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return Numbers.LONG_NULL;
        }
        return UNSAFE.getLong(colAddr + (row << 4));
    }

    public static short readShort(long dataAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return 0;
        }
        return UNSAFE.getShort(colAddr + (row << 1));
    }

    // --- Var-size header reads ---

    public static long readBinaryHeader(long dataAddress, long varSizeAuxAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return -1L;
        }
        long auxAddr = UNSAFE.getLong(varSizeAuxAddress + ((long) columnIndex << 3));
        long dataOffset = UNSAFE.getLong(auxAddr + (row << 3));
        return UNSAFE.getLong(colAddr + dataOffset);
    }

    public static int readStringHeader(long dataAddress, long varSizeAuxAddress, int columnIndex, long row) {
        long colAddr = UNSAFE.getLong(dataAddress + ((long) columnIndex << 3));
        if (colAddr == 0) {
            return -1;
        }
        long auxAddr = UNSAFE.getLong(varSizeAuxAddress + ((long) columnIndex << 3));
        long dataOffset = UNSAFE.getLong(auxAddr + (row << 3));
        return UNSAFE.getInt(colAddr + dataOffset);
    }

    public static long readVarcharHeader(long varSizeAuxAddress, int columnIndex, long row) {
        long auxAddr = UNSAFE.getLong(varSizeAuxAddress + ((long) columnIndex << 3));
        if (auxAddr == 0) {
            return 4L; // VARCHAR_HEADER_FLAG_NULL
        }
        return UNSAFE.getLong(auxAddr + (row << 4));
    }

    // --- Bind variable reads ---

    public static byte readVarByte(long varsAddress, int byteOffset) {
        return UNSAFE.getByte(varsAddress + byteOffset);
    }

    public static double readVarDouble(long varsAddress, int byteOffset) {
        return UNSAFE.getDouble(varsAddress + byteOffset);
    }

    public static float readVarFloat(long varsAddress, int byteOffset) {
        return UNSAFE.getFloat(varsAddress + byteOffset);
    }

    public static int readVarInt(long varsAddress, int byteOffset) {
        return UNSAFE.getInt(varsAddress + byteOffset);
    }

    public static long readVarLong(long varsAddress, int byteOffset) {
        return UNSAFE.getLong(varsAddress + byteOffset);
    }

    public static short readVarShort(long varsAddress, int byteOffset) {
        return UNSAFE.getShort(varsAddress + byteOffset);
    }

    public static long readVarLong128Hi(long varsAddress, int byteOffset) {
        return UNSAFE.getLong(varsAddress + byteOffset + Long.BYTES);
    }

    // --- Output writes ---

    public static void writeRow(long filteredRowsAddress, long outputIndex, long row) {
        UNSAFE.putLong(filteredRowsAddress + (outputIndex << 3), row);
    }

    // --- Float comparisons with epsilon ---

    public static boolean doubleEq(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= DOUBLE_EPSILON;
    }

    public static boolean doubleGe(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= DOUBLE_EPSILON || a >= b;
    }

    public static boolean doubleGt(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return false;
        }
        return Math.abs(a - b) > DOUBLE_EPSILON && a > b;
    }

    public static boolean doubleLe(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= DOUBLE_EPSILON || a <= b;
    }

    public static boolean doubleLt(double a, double b) {
        boolean aNaN = Double.isNaN(a);
        boolean bNaN = Double.isNaN(b);
        if (aNaN || bNaN) {
            return false;
        }
        return Math.abs(a - b) > DOUBLE_EPSILON && a < b;
    }

    public static boolean doubleNe(double a, double b) {
        return !doubleEq(a, b);
    }

    public static boolean floatEq(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= FLOAT_EPSILON;
    }

    public static boolean floatGe(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= FLOAT_EPSILON || a >= b;
    }

    public static boolean floatGt(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return false;
        }
        return Math.abs(a - b) > FLOAT_EPSILON && a > b;
    }

    public static boolean floatLe(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return aNaN && bNaN;
        }
        return Math.abs(a - b) <= FLOAT_EPSILON || a <= b;
    }

    public static boolean floatLt(float a, float b) {
        boolean aNaN = Float.isNaN(a);
        boolean bNaN = Float.isNaN(b);
        if (aNaN || bNaN) {
            return false;
        }
        return Math.abs(a - b) > FLOAT_EPSILON && a < b;
    }

    public static boolean floatNe(float a, float b) {
        return !floatEq(a, b);
    }

    // --- Integer comparisons (full-path: handles both null and non-null) ---

    public static boolean intEq(int a, int b) {
        return a == b;
    }

    public static boolean intGe(int a, int b) {
        return a >= b;
    }

    public static boolean intGt(int a, int b) {
        return a > b;
    }

    public static boolean intLe(int a, int b) {
        return a <= b;
    }

    public static boolean intLt(int a, int b) {
        return a < b;
    }

    public static boolean intNe(int a, int b) {
        return a != b;
    }

    // Null-aware: when at least one operand is INT_NULL
    public static boolean intNullEq(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return a == b;
        }
        return a == b;
    }

    public static boolean intNullGe(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return a == b;
        }
        return a >= b;
    }

    public static boolean intNullGt(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return false;
        }
        return a > b;
    }

    public static boolean intNullLe(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return a == b;
        }
        return a <= b;
    }

    public static boolean intNullLt(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return false;
        }
        return a < b;
    }

    public static boolean intNullNe(int a, int b) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL) {
            return a != b;
        }
        return a != b;
    }

    // --- Long comparisons ---

    public static boolean longEq(long a, long b) {
        return a == b;
    }

    public static boolean longGe(long a, long b) {
        return a >= b;
    }

    public static boolean longGt(long a, long b) {
        return a > b;
    }

    public static boolean longLe(long a, long b) {
        return a <= b;
    }

    public static boolean longLt(long a, long b) {
        return a < b;
    }

    public static boolean longNe(long a, long b) {
        return a != b;
    }

    // Null-aware long comparisons
    public static boolean longNullEq(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return a == b;
        }
        return a == b;
    }

    public static boolean longNullGe(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return a == b;
        }
        return a >= b;
    }

    public static boolean longNullGt(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return false;
        }
        return a > b;
    }

    public static boolean longNullLe(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return a == b;
        }
        return a <= b;
    }

    public static boolean longNullLt(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return false;
        }
        return a < b;
    }

    public static boolean longNullNe(long a, long b) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL) {
            return a != b;
        }
        return a != b;
    }

    // --- Null-aware type coercions ---

    public static double coerceIntToDouble(int value) {
        return value == Numbers.INT_NULL ? Double.NaN : (double) value;
    }

    public static float coerceIntToFloat(int value) {
        return value == Numbers.INT_NULL ? Float.NaN : (float) value;
    }

    public static long coerceIntToLong(int value) {
        return value == Numbers.INT_NULL ? Numbers.LONG_NULL : (long) value;
    }

    public static double coerceLongToDouble(long value) {
        return value == Numbers.LONG_NULL ? Double.NaN : (double) value;
    }

    // --- Null-aware arithmetic ---

    public static int intArithmeticNull(int a, int b, int opcode) {
        if (a == Numbers.INT_NULL || b == Numbers.INT_NULL || (opcode == 17 && b == 0)) {
            return Numbers.INT_NULL;
        }
        return switch (opcode) {
            case 14 -> a + b; // ADD
            case 15 -> a - b; // SUB
            case 16 -> a * b; // MUL
            case 17 -> a / b; // DIV
            default -> throw new IllegalArgumentException("unsupported int opcode: " + opcode);
        };
    }

    public static long longArithmeticNull(long a, long b, int opcode) {
        if (a == Numbers.LONG_NULL || b == Numbers.LONG_NULL || (opcode == 17 && b == 0)) {
            return Numbers.LONG_NULL;
        }
        return switch (opcode) {
            case 14 -> a + b; // ADD
            case 15 -> a - b; // SUB
            case 16 -> a * b; // MUL
            case 17 -> a / b; // DIV
            default -> throw new IllegalArgumentException("unsupported long opcode: " + opcode);
        };
    }

    // --- Float/double division (return NaN on div-by-zero) ---

    public static float floatDiv(float a, float b) {
        if (Float.isNaN(a) || Float.isNaN(b) || b == 0) {
            return Float.NaN;
        }
        return a / b;
    }

    public static double doubleDiv(double a, double b) {
        if (Double.isNaN(a) || Double.isNaN(b) || b == 0) {
            return Double.NaN;
        }
        return a / b;
    }

    // --- Float/double null-aware arithmetic (NaN propagation) ---

    public static float floatArithmeticNull(float a, float b, int opcode) {
        if (Float.isNaN(a) || Float.isNaN(b)) {
            return Float.NaN;
        }
        return switch (opcode) {
            case 14 -> a + b; // ADD
            case 15 -> a - b; // SUB
            case 16 -> a * b; // MUL
            case 17 -> b == 0 ? Float.NaN : a / b; // DIV
            default -> throw new IllegalArgumentException("unsupported float opcode: " + opcode);
        };
    }

    public static double doubleArithmeticNull(double a, double b, int opcode) {
        if (Double.isNaN(a) || Double.isNaN(b)) {
            return Double.NaN;
        }
        return switch (opcode) {
            case 14 -> a + b; // ADD
            case 15 -> a - b; // SUB
            case 16 -> a * b; // MUL
            case 17 -> b == 0 ? Double.NaN : a / b; // DIV
            default -> throw new IllegalArgumentException("unsupported double opcode: " + opcode);
        };
    }

    // --- I128 (UUID) comparisons ---

    public static boolean i128Eq(long loA, long hiA, long loB, long hiB) {
        return loA == loB && hiA == hiB;
    }

    public static boolean i128Ne(long loA, long hiA, long loB, long hiB) {
        return loA != loB || hiA != hiB;
    }

    private FilterHelpers() {
    }
}
