name: Rebuild MacOS ARM and Push to PR
on:
  workflow_dispatch:

# This workflow is triggered manually from the Actions tab.

jobs:
  rebuild:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v3
      - name: Install tooling
        run: |
          brew install make cmake gcc
      - name: Build the lib
        run: |
          cd core
          cmake -B build/release -DCMAKE_BUILD_TYPE=Release
          cmake --build build/release --config Release
          cd ..
      - name: Commit the file
        run: |
          git config --global user.name 'GitHub Actions - ARM build'
          git config --global user.email 'jaromir@questdb.io'
          git add core/src/main/resources/io/questdb/bin/armosx/libquestdb.dylib
          git commit -m "Rebuild MacOS ARM"
      - name: Push the file to the current branch
        uses: ad-m/github-push-action@d91a48109
        # Why do we use a commit hash instead of a tag for the github-push-action?
        # ad-m/github-push-action is not as well-known repo as e.g. actions/checkout and therefore we trust it less.
        # d91a48109 is the same as the tag v0.8.0, but it's guaranteed to be immutable.
        # So even if a bad actor takes over the repo, and rewrites tags to point to malicious commits, we will still be safe.
        with:
          branch: ${{ github.head_ref }}

